spring:
  profiles:
    active:
      - development
  config:
    import:
      - "configtree:./"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format-sql: true
